name: Containerize Automation
on:
  push:
    branches:
      - dev
jobs:
  edit_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check yq
        run: yq --version
  push_to_registry:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-node-app:latest
  deply_to_k8s:
    name: Deploy to K8S
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Connect K8S Cluster
        run: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy
        run: kubectl apply -f ./manifest/.
