name: CodeQL Analysis

on:
  push:
    branches:
      - dev

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [javascript]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Build and analyze
        uses: github/codeql-action/analyze@v2
